/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.table.*;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import java.awt.event.*;
/**
 *
 * @author IP
 */
public class loginframe extends javax.swing.JFrame {
          public loginframe() {
        initComponents();
        Timer t= new Timer(1000,new ActionListener(){
        public void actionPerformed(ActionEvent e){
        int sec=Integer.parseInt(sect.getText());
        int min=Integer.parseInt(mint.getText());
        int hr=Integer.parseInt(hrt.getText());
        sec++;
                }       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        one = new javax.swing.JFrame();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        two = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        a = new javax.swing.JButton();
        b = new javax.swing.JButton();
        c = new javax.swing.JButton();
        d = new javax.swing.JButton();
        g = new javax.swing.JButton();
        f = new javax.swing.JButton();
        h = new javax.swing.JButton();
        i = new javax.swing.JButton();
        l = new javax.swing.JButton();
        m = new javax.swing.JButton();
        n = new javax.swing.JButton();
        o = new javax.swing.JButton();
        k = new javax.swing.JButton();
        j = new javax.swing.JButton();
        e = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel27 = new javax.swing.JLabel();
        three = new javax.swing.JFrame();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        four = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel25 = new javax.swing.JLabel();

        one.getContentPane().setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel5.setText("Name");
        one.getContentPane().add(jLabel5);
        jLabel5.setBounds(138, 82, 42, 17);

        jLabel7.setText("jLabel7");
        one.getContentPane().add(jLabel7);
        jLabel7.setBounds(392, 125, 34, 0);

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel8.setText("Date of Birth (yyyy/mm/dd)");
        one.getContentPane().add(jLabel8);
        jLabel8.setBounds(140, 140, 200, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel9.setText("Email");
        one.getContentPane().add(jLabel9);
        jLabel9.setBounds(140, 360, 67, 17);

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel10.setText("Phone No.");
        one.getContentPane().add(jLabel10);
        jLabel10.setBounds(140, 310, 90, 17);

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel11.setText("Class");
        one.getContentPane().add(jLabel11);
        jLabel11.setBounds(140, 250, 60, 17);
        one.getContentPane().add(txt1);
        txt1.setBounds(438, 74, 280, 40);
        one.getContentPane().add(jTextField3);
        jTextField3.setBounds(438, 125, 280, 40);
        one.getContentPane().add(jTextField7);
        jTextField7.setBounds(440, 230, 284, 40);

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        one.getContentPane().add(jTextField8);
        jTextField8.setBounds(440, 290, 284, 40);
        one.getContentPane().add(jTextField9);
        jTextField9.setBounds(440, 340, 284, 40);

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jLabel12.setText("Sign Up");
        one.getContentPane().add(jLabel12);
        jLabel12.setBounds(240, 10, 140, 60);

        jButton3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton3.setText("Enter");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        one.getContentPane().add(jButton3);
        jButton3.setBounds(290, 370, 102, 82);
        one.getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(440, 180, 280, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel6.setText("Password");
        one.getContentPane().add(jLabel6);
        jLabel6.setBounds(140, 200, 86, 17);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/two.jpg"))); // NOI18N
        jLabel26.setText("jLabel26");
        one.getContentPane().add(jLabel26);
        jLabel26.setBounds(0, 0, 900, 550);

        two.getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel13.setText("Name");

        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel14.setText("Class");

        jLabel15.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel15.setText("Roll no");

        jLabel22.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel23.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel24.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13))
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(0, 24, Short.MAX_VALUE))
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        two.getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 80, 356, 171);

        jButton5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton5.setText("Submit Test");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        two.getContentPane().add(jButton5);
        jButton5.setBounds(535, 38, 130, 90);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel16.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));
        two.getContentPane().add(jLabel16);
        jLabel16.setBounds(390, 210, 60, 38);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel17.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));
        two.getContentPane().add(jLabel17);
        jLabel17.setBounds(450, 210, 581, 38);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.lightGray));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("         P                         C                          M");

        a.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        a.setText("Q 1");
        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });

        b.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        b.setText("Q.2");
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });

        c.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        c.setText("Q.3");
        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });

        d.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        d.setText("Q.4");
        d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dActionPerformed(evt);
            }
        });

        g.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        g.setText("Q.7");
        g.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gActionPerformed(evt);
            }
        });

        f.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        f.setText("Q.6");
        f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fActionPerformed(evt);
            }
        });

        h.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        h.setText("Q.8");
        h.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hActionPerformed(evt);
            }
        });

        i.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        i.setText("Q.9");
        i.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iActionPerformed(evt);
            }
        });

        l.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        l.setText("Q.12");
        l.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lActionPerformed(evt);
            }
        });

        m.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        m.setText("Q.13");
        m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mActionPerformed(evt);
            }
        });

        n.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        n.setText("Q.14");
        n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nActionPerformed(evt);
            }
        });

        o.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        o.setText("Q.15");
        o.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oActionPerformed(evt);
            }
        });

        k.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        k.setText("Q.11");
        k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kActionPerformed(evt);
            }
        });

        j.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        j.setText("Q.10");
        j.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jActionPerformed(evt);
            }
        });

        e.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        e.setText("Q.5");
        e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(a, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(c, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(d, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(e, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(g, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(f, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(h, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(i, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(24, 24, 24)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(l)
                        .addComponent(m)
                        .addComponent(n)
                        .addComponent(k))
                    .addComponent(o, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(a)
                            .addComponent(f)
                            .addComponent(k))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b)
                            .addComponent(g)
                            .addComponent(l))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c)
                            .addComponent(h)
                            .addComponent(m))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(d)
                            .addComponent(i)
                            .addComponent(n))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(j)
                            .addComponent(o)
                            .addComponent(e))
                        .addGap(0, 37, Short.MAX_VALUE))
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        two.getContentPane().add(jPanel2);
        jPanel2.setBounds(30, 280, 339, 250);

        jButton7.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton7.setText("<");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        two.getContentPane().add(jButton7);
        jButton7.setBounds(340, 560, 60, 60);

        jButton8.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton8.setText(">");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        two.getContentPane().add(jButton8);
        jButton8.setBounds(430, 560, 60, 60);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton1.setText("k");
        jRadioButton1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton1ItemStateChanged(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton2.setText("jRadioButton2");
        jRadioButton2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton2ItemStateChanged(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton3.setText("jRadioButton3");
        jRadioButton3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton3ItemStateChanged(evt);
            }
        });

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton4.setText("jRadioButton4");
        jRadioButton4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton4ItemStateChanged(evt);
            }
        });

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4))
                .addContainerGap(199, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jRadioButton2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(11, Short.MAX_VALUE)
                        .addComponent(jRadioButton1)
                        .addGap(57, 57, 57)))
                .addComponent(jRadioButton3)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton4)
                .addGap(31, 31, 31))
            .addComponent(jSeparator3)
        );

        two.getContentPane().add(jPanel3);
        jPanel3.setBounds(460, 330, 360, 190);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/three.jpg"))); // NOI18N
        two.getContentPane().add(jLabel27);
        jLabel27.setBounds(0, -4, 1050, 710);

        three.getContentPane().setLayout(null);

        jLabel19.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Result");
        three.getContentPane().add(jLabel19);
        jLabel19.setBounds(220, 10, 120, 80);

        jLabel20.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Score card");
        three.getContentPane().add(jLabel20);
        jLabel20.setBounds(80, 100, 130, 70);

        jLabel21.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Performance");
        three.getContentPane().add(jLabel21);
        jLabel21.setBounds(80, 190, 160, 32);
        three.getContentPane().add(jTextField6);
        jTextField6.setBounds(340, 110, 115, 38);
        three.getContentPane().add(jTextField10);
        jTextField10.setBounds(340, 180, 115, 38);

        jButton4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        three.getContentPane().add(jButton4);
        jButton4.setBounds(90, 280, 220, 80);

        jButton6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton6.setText("Solutions To Incorrect Answer");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        three.getContentPane().add(jButton6);
        jButton6.setBounds(370, 280, 260, 80);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/download.jpg"))); // NOI18N
        three.getContentPane().add(jLabel28);
        jLabel28.setBounds(0, 0, 714, 400);

        jTable1.setBackground(new java.awt.Color(153, 0, 102));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Question number", "question", "answer"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout fourLayout = new javax.swing.GroupLayout(four.getContentPane());
        four.getContentPane().setLayout(fourLayout);
        fourLayout.setHorizontalGroup(
            fourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
        );
        fourLayout.setVerticalGroup(
            fourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 0, 51));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setText("Ussername");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 80, 90, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setText("Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 140, 90, 17);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(300, 70, 220, 40);

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton1.setText("PROCEED");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(200, 200, 101, 48);

        jButton2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton2.setText("SIGN UP");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(300, 300, 93, 48);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel3.setText("LOGIN");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(140, 10, 73, 41);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setText("Are you a new user?");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 297, 150, 50);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(300, 120, 220, 40);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plain-color-hd-wallpapers-851x315.jpg"))); // NOI18N
        jLabel25.setText("jLabel25");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(0, 0, 620, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
one.show(); 

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
a.doClick();
String name="",cl="",usnm="";int phno=0;
        int f=1;
        String nm=jTextField1.getText();
String pwd=new String(jPasswordField1.getPassword());
try
       {
       Class.forName("java.sql.Driver");
            System.out.println(1);
       Connection con=DriverManager.getConnection("jdbc:mysql://localhost/project","root","abcd");
            System.out.println(2);
       Statement stmt = con.createStatement();
            System.out.println(3);
       String query="select * from stuinfo where usnm='"+nm+"' and pwd='"+pwd+"' ;";
            System.out.println(query);
            ResultSet rs=stmt.executeQuery(query);
                   System.out.println(5);
            while(rs.next())
            {String h=rs.getString("usnm");
            String p=rs.getString("pwd");
                if (h.equals(nm) && p.equals(pwd))
                   {f=2;
                    name=rs.getString(1);
                    cl=rs.getString(4);
                   usnm=rs.getString(7);
                  phno=rs.getInt(5);
                   break;
                  }
            }
            if(f==2)
     {
         two.show();
          jLabel22.setText(""+name);
         jLabel23.setText(""+cl);
         jLabel24.setText(""+phno);
     }
else
    JOptionPane.showMessageDialog(null,"invalid usserid or password");
            rs.close();
            stmt.close();
            con.close();
            
       }
     catch (Exception e){
         
     JOptionPane.showMessageDialog(null,e.getMessage());
     }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        String str=txt1.getText();
String dat=jTextField3.getText();
String roll=jTextField8.getText();
char ch=Character.toLowerCase(str.charAt(0));
str=str.replace(str.charAt(0),ch);
String d=jTextField3.getText();

String usnm=str.substring(0,1)+"@"+str.substring(1);
JOptionPane.showMessageDialog(null,"Your user name is "+usnm);
String pwd=new String(jPasswordField2.getPassword());
int n=Integer.parseInt(jTextField8.getText());
try
       {
       Class.forName("java.sql.Driver");
            System.out.println(6);
       Connection con=DriverManager.getConnection("jdbc:mysql://localhost/project","root","abcd");
            System.out.println(7);
       Statement stmt = con.createStatement();
            System.out.println(8);
       String query="insert into stuinfo values('"+txt1.getText()+"','"+jTextField3.getText()+"','"+pwd+"','"+jTextField7.getText()+"',"+n+",'"+jTextField9.getText()+"','"+usnm+"');";
            System.out.println(query);
       stmt.executeUpdate(query);
            System.out.println(9);
            stmt.close();
            con.close();
       two.show();     
       }
     catch (Exception e){
     JOptionPane.showMessageDialog(null, "error");
     }
     a.doClick();
          two.show();
          jLabel22.setText(""+str);
         jLabel23.setText(""+dat);
         jLabel24.setText(""+roll);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
int score=0;
        int n=JOptionPane.showConfirmDialog(null,"are you sure about submiting the test");        // TODO add your handling code here:
if(n==0)
two.dispose();
three.show();
if(n==1)
        two.show();
if(n==2)
        two.show();
try
       {
       Class.forName("java.sql.Driver");
            System.out.println('s');
       Connection con=DriverManager.getConnection("jdbc:mysql://localhost/project","root","abcd");
            System.out.println('s');
       Statement stmt = con.createStatement();
            System.out.println('s');
       String query="select sum(marks) as 'totalmarks' from marks;";
            System.out.println(query);
            ResultSet rs=stmt.executeQuery(query);
                   System.out.println('s');
            while(rs.next())
            { score=rs.getInt("totalmarks");
                            
            }
          System.out.println('s');
            rs.close();
            stmt.close();
            con.close();
            
       }
     catch (Exception e){
         
     JOptionPane.showMessageDialog(null,e.getMessage());
     }
jTextField6.setText(""+score);

{                                            
int marks=Integer.parseInt(jTextField6.getText());
String per;
if(marks>50)
    per="Excellent";
else if(marks>40)
        per="Very Good";
else if(marks>30)
        per="Good";
else if(marks>20)
        per="Average";
else
    per="Below Average";
jTextField10.setText(""+per);

    }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed

                  
        jLabel17.setText("How closer the satelliteto earth the speed should be");
           jRadioButton1.setText("move slow ");
         jRadioButton2.setText("move fast");
         jRadioButton3.setText("constant speed");
         jRadioButton4.setText("0");
        jLabel16.setText("a");
        
            
        
    }//GEN-LAST:event_aActionPerformed

    private void lActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lActionPerformed
 buttonGroup1.clearSelection();;  
        jLabel16.setText("l");
         jLabel17.setText("What is intgral of tan(x)");
         jRadioButton1.setText("sec(x)tan(x)");
         jRadioButton2.setText("log(sec(x))");
         jRadioButton3.setText("-log(cos(x))");
         jRadioButton4.setText("both b and c");
         //ans:4
         
    }//GEN-LAST:event_lActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
String qno=jLabel16.getText();
  buttonGroup1.clearSelection();
buttonGroup1.clearSelection();;
        
        if(qno=="a")
        {
            
        b.doClick();
        
        }
        else 
            if(qno=="b")
        { c.doClick();
     
        }
          if(qno=="c")
        { d.doClick();
        
        }
        else 
            if(qno=="d")
        { e.doClick();
        
        }
            if(qno=="e")
        { f.doClick();
        
        }
        else 
            if(qno=="f")
        { g.doClick();
        
        }
              if(qno=="g")
        { h.doClick();
        
        }
        else 
            if(qno=="h")
        { i.doClick();
        
        }
                if(qno=="i")
        { j.doClick();
        
        }
        else 
            if(qno=="j")
        { k.doClick();
        
        }  if(qno=="k")
        { l.doClick();
        
        }
        else 
            if(qno=="l")
        { m.doClick();
        
        }
          if(qno=="m")
        { n.doClick();
        
        }
        else 
            if(qno=="n")
        { o.doClick();
        
        }
        
       
                
// TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
String qno=jLabel16.getText();
buttonGroup1.clearSelection();
        
        
            if(qno=="b")
        { a.doClick();
        
        }
          if(qno=="c")
        { b.doClick();
        
        }
        else 
            if(qno=="d")
        { c.doClick();
        
        }
            if(qno=="e")
        { d.doClick();
        
        }
        else 
            if(qno=="f")
        { e.doClick();
        
        }
              if(qno=="g")
        { f.doClick();
        
        }
        else 
            if(qno=="h")
        { g.doClick();
        
        }
                if(qno=="i")
        { h.doClick();
        
        }
        else 
            if(qno=="j")
        { i.doClick();
        
        }  if(qno=="k")
        { j.doClick();
        
        }
        else 
            if(qno=="l")
        { k.doClick();
        
        }
          if(qno=="m")
        { l.doClick();
        
        }
        else 
            if(qno=="n")
        { m.doClick();
        
        }
            if(qno=="o")
        { n.doClick();
        
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
 buttonGroup1.clearSelection();;         
        jLabel17.setText("The current enterring and leaving a point in a circuit should be");
         jRadioButton1.setText("decreasing ");
         jRadioButton2.setText("increasing");
         jRadioButton3.setText("variable");
         jRadioButton4.setText("equal");
          jLabel16.setText("b");
        
         
         
    }//GEN-LAST:event_bActionPerformed

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
 buttonGroup1.clearSelection();;
        jLabel16.setText("c");
          jLabel17.setText("The process in which ac is converted to dc is called");
           jRadioButton1.setText("retrification");
         jRadioButton2.setText("induction");
         jRadioButton3.setText("inversion ");
         jRadioButton4.setText("none of above");
         if (jRadioButton1.isSelected()){ 
    }
    }//GEN-LAST:event_cActionPerformed

    private void dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dActionPerformed
 buttonGroup1.clearSelection();;        
        jLabel17.setText("The unification of electromagnet and weak nuclear forces was done by :");
           jRadioButton1.setText("Faraday");
         jRadioButton2.setText("Maxwell");
         jRadioButton3.setText("Abdus Salam");
         jRadioButton4.setText("Kirchhoff");
        jLabel16.setText("d");
        if (jRadioButton3.isSelected()){ 
    }
    }//GEN-LAST:event_dActionPerformed

    private void fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fActionPerformed

         buttonGroup1.clearSelection();;  
         jLabel16.setText("f");
         jLabel17.setText("In a dry cell, the electrolyte paste is formed by ");
         jRadioButton1.setText("ammonium sulphate");
         jRadioButton2.setText("ammonium chloride");
         jRadioButton3.setText("zinc sulphate");
         jRadioButton4.setText("none of above");//ans:2
         
       
    }//GEN-LAST:event_fActionPerformed

    private void gActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gActionPerformed
 buttonGroup1.clearSelection();;  
        jLabel16.setText("g");
          jLabel17.setText("Non conductors include");
         jRadioButton1.setText("Plastics");
         jRadioButton2.setText("non metals");
         jRadioButton3.setText("none of above");
         jRadioButton4.setText("both a and b");
         //ans:4
      
    }//GEN-LAST:event_gActionPerformed

    private void hActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hActionPerformed
                buttonGroup1.clearSelection();;  
        jLabel16.setText("h");
                 jLabel17.setText("With acid universal indicators show colour");
         jRadioButton1.setText("blue");
         jRadioButton2.setText("red");
         jRadioButton3.setText("violet");
         jRadioButton4.setText("green");
         //ans:4
                

    }//GEN-LAST:event_hActionPerformed

    private void iActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iActionPerformed

         buttonGroup1.clearSelection();;  
         jLabel16.setText("i");
jLabel17.setText("The purpose o Lean Burn engine is to");
         jRadioButton1.setText("consume less oxygen");
         jRadioButton2.setText("produce less air pollution ");
         jRadioButton3.setText("Use them in sky rokets");
         jRadioButton4.setText("produce more efficient fuel combustion");
         //ans:4 
 
    }//GEN-LAST:event_iActionPerformed

    private void jActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jActionPerformed

         buttonGroup1.clearSelection();; 
         jLabel16.setText("j");  
jLabel17.setText("The ability of dissolving animal fat is found in");
         jRadioButton1.setText("liquid carbon dioxide");
         jRadioButton2.setText("carbon dioxide");
         jRadioButton3.setText("all of these");
         jRadioButton4.setText("gaseous carbon dioxide");
         //ans:4
      if (jRadioButton1.isSelected()){ 
    }
    // TODO add your handling code here:
    }//GEN-LAST:event_jActionPerformed

    private void kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kActionPerformed
 buttonGroup1.clearSelection();;  
        jLabel16.setText("k");     
jLabel17.setText("What is the differential coeffiecient of cos(x)");
         jRadioButton1.setText("sin(x)");
         jRadioButton2.setText("-sin(x)");
         jRadioButton3.setText("cot(x");
         jRadioButton4.setText("tan(x");
         //ans:4 

    }//GEN-LAST:event_kActionPerformed

    private void mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mActionPerformed
 buttonGroup1.clearSelection();;  
        jLabel16.setText("m"); 
 jLabel17.setText("What is the integral of sec(x)");
         jRadioButton1.setText("log(sec(x)+tan(x))");
         jRadioButton2.setText("log(sec(x)-tan(x))");
         jRadioButton3.setText("log(tan(3.14/2+x/2))");
         jRadioButton4.setText("both a and c ");
         //ans:4

    }//GEN-LAST:event_mActionPerformed

    private void nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nActionPerformed
 buttonGroup1.clearSelection();;  
jLabel16.setText("n");
jLabel17.setText("which is true for eccentricity of hyperbola?");
         jRadioButton1.setText("e>1");
         jRadioButton2.setText("e=0");
         jRadioButton3.setText("e<1");
         jRadioButton4.setText("none of the above");
         //ans:1 
 
    }//GEN-LAST:event_nActionPerformed

    private void oActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oActionPerformed
 buttonGroup1.clearSelection();;  
        jLabel16.setText("o"); 
 jLabel17.setText("what is the integral of cot(x)");
         jRadioButton1.setText("log(sin(x))");
         jRadioButton2.setText("log(cosec(x)-cot(x))");
         jRadioButton3.setText("both a and b");
         jRadioButton4.setText("none of the above");
         //ans:4
 
    }//GEN-LAST:event_oActionPerformed

    private void eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eActionPerformed
 buttonGroup1.clearSelection();;  
        jLabel17.setText("I we get a straight line with a positive slope then accceleration will be "); 
         jRadioButton1.setText("increasing");
         jRadioButton2.setText("decreasing");
         jRadioButton3.setText("constant");
         jRadioButton4.setText("zero");
 jLabel16.setText("e"); 
 // TODO add your handling code here:
                        // TODO add your handling code here:
    }//GEN-LAST:event_eActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
  int i,n=15;
  for(i=1;i<=n;i++){
        try
      {
       Class.forName("java.sql.Driver");
            System.out.println(1);
       Connection con=DriverManager.getConnection("jdbc:mysql://localhost/project","root","abcd");
            System.out.println(2);
       Statement stmt = con.createStatement();
            System.out.println(3);
       String query="update marks set marks=null where qno="+i+";";
            System.out.println(query);
       stmt.executeUpdate(query);
            System.out.println(5);
            stmt.close();
            con.close();
            
       }
     catch (Exception e){
     JOptionPane.showMessageDialog(null, "error");
     }}
   System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jRadioButton1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton1ItemStateChanged
        char ch=jLabel16.getText().charAt(0);
        if(ch=='a'){
        if (jRadioButton1.isSelected()==true){ try
      {
       Class.forName("java.sql.Driver");
            System.out.println(30);
       Connection con=DriverManager.getConnection("jdbc:mysql://localhost/project","root","abcd");
            System.out.println(31);
       Statement stmt = con.createStatement();
            System.out.println(32);
       String query="update marks set marks=4 where qno="+1+";";
            System.out.println(query);
       stmt.executeUpdate(query);
            System.out.println(33);
            stmt.close();
            con.close();
            
       }
     catch (Exception e){
     JOptionPane.showMessageDialog(null, "error");
     }
         }
         }
        if(ch=='c'){
        if (jRadioButton1.isSelected()){ try
      {
       Class.forName("java.sql.Driver");
            System.out.println(30);
       Connection con=DriverManager.getConnection("jdbc:mysql://localhost/project","root","abcd");
            System.out.println(31);
       Statement stmt = con.createStatement();
            System.out.println(32);
       String query="update marks set marks=4 where qno="+3+";";
            System.out.println(query);
       stmt.executeUpdate(query);
            System.out.println(33);
            stmt.close();
            con.close();
            
       }
     catch (Exception e){
     JOptionPane.showMessageDialog(null, "error");
     }
         }
         }
        if(ch=='j'){
        if (jRadioButton1.isSelected()){ try
      {
       Class.forName("java.sql.Driver");
            System.out.println(30);
       Connection con=DriverManager.getConnection("jdbc:mysql://localhost/project","root","abcd");
            System.out.println(31);
       Statement stmt = con.createStatement();
            System.out.println(32);
       String query="update marks set marks=4 where qno="+10+";";
            System.out.println(query);
       stmt.executeUpdate(query);
            System.out.println(33);
            stmt.close();
            con.close();
            
       }
     catch (Exception e){
     JOptionPane.showMessageDialog(null, "error");
     }
         }
         }
        if(ch=='n'){
        if (jRadioButton1.isSelected()){ try
      {
       Class.forName("java.sql.Driver");
            System.out.println(30);
       Connection con=DriverManager.getConnection("jdbc:mysql://localhost/project","root","abcd");
            System.out.println(31);
       Statement stmt = con.createStatement();
            System.out.println(32);
       String query="update marks set marks=4 where qno="+14+";";
            System.out.println(query);
       stmt.executeUpdate(query);
            System.out.println(33);
            stmt.close();
            con.close();
            
       }
     catch (Exception e){
     JOptionPane.showMessageDialog(null, "error");
     }
         }
        }
    }//GEN-LAST:event_jRadioButton1ItemStateChanged

    private void jRadioButton3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton3ItemStateChanged
char ch=jLabel16.getText().charAt(0);
       
if(ch=='d'){
        if (jRadioButton3.isSelected()){ try
      {
       Class.forName("java.sql.Driver");
            System.out.println(30);
       Connection con=DriverManager.getConnection("jdbc:mysql://localhost/project","root","abcd");
            System.out.println(31);
       Statement stmt = con.createStatement();
            System.out.println(32);
       String query="update marks set marks=4 where qno="+4+";";
            System.out.println(query);
       stmt.executeUpdate(query);
            System.out.println(33);
            stmt.close();
            con.close();
            
       }
     catch (Exception e){
     JOptionPane.showMessageDialog(null, "error");
     }
         }
         }
    if(ch=='e'){
        if (jRadioButton3.isSelected()){ try
      {
       Class.forName("java.sql.Driver");
            System.out.println(30);
       Connection con=DriverManager.getConnection("jdbc:mysql://localhost/project","root","abcd");
            System.out.println(31);
       Statement stmt = con.createStatement();
            System.out.println(32);
       String query="update marks set marks=4 where qno="+5+";";
            System.out.println(query);
       stmt.executeUpdate(query);
            System.out.println(33);
            stmt.close();
            con.close();
            
       }
     catch (Exception e){
     JOptionPane.showMessageDialog(null, "error");
     }
         }
        }
    

    }//GEN-LAST:event_jRadioButton3ItemStateChanged

    private void jRadioButton2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton2ItemStateChanged
      char ch=jLabel16.getText().charAt(0);
       
if(ch=='b'){
        if (jRadioButton2.isSelected()){ try
      {
       Class.forName("java.sql.Driver");
            System.out.println(30);
       Connection con=DriverManager.getConnection("jdbc:mysql://localhost/project","root","abcd");
            System.out.println(31);
       Statement stmt = con.createStatement();
            System.out.println(32);
       String query="update marks set marks=4 where qno="+2+";";
            System.out.println(query);
       stmt.executeUpdate(query);
            System.out.println(33);
            stmt.close();
            con.close();
            
       }
     catch (Exception e){
     JOptionPane.showMessageDialog(null, "error");
     }
         }
         }
if(ch=='f'){
        if (jRadioButton2.isSelected()){ try
      {
       Class.forName("java.sql.Driver");
            System.out.println(30);
       Connection con=DriverManager.getConnection("jdbc:mysql://localhost/project","root","abcd");
            System.out.println(31);
       Statement stmt = con.createStatement();
            System.out.println(32);
       String query="update marks set marks=4 where qno="+6+";";
            System.out.println(query);
       stmt.executeUpdate(query);
            System.out.println(33);
            stmt.close();
            con.close();
            
       }
     catch (Exception e){
     JOptionPane.showMessageDialog(null, "error");
     }
         }
         }
if(ch=='h'){
        if (jRadioButton2.isSelected()){ try
      {
       Class.forName("java.sql.Driver");
            System.out.println(30);
       Connection con=DriverManager.getConnection("jdbc:mysql://localhost/project","root","abcd");
            System.out.println(31);
       Statement stmt = con.createStatement();
            System.out.println(32);
       String query="update marks set marks=4 where qno="+8+";";
            System.out.println(query);
       stmt.executeUpdate(query);
            System.out.println(33);
            stmt.close();
            con.close();
            
       }
     catch (Exception e){
     JOptionPane.showMessageDialog(null, "error");
     }
         }
        }
if(ch=='k'){
        if (jRadioButton2.isSelected()){ try
      {
       Class.forName("java.sql.Driver");
            System.out.println(30);
       Connection con=DriverManager.getConnection("jdbc:mysql://localhost/project","root","abcd");
            System.out.println(31);
       Statement stmt = con.createStatement();
            System.out.println(32);
       String query="update marks set marks=4 where qno="+11+";";
            System.out.println(query);
       stmt.executeUpdate(query);
            System.out.println(33);
            stmt.close();
            con.close();
            
       }
     catch (Exception e){
     JOptionPane.showMessageDialog(null, "error");
     }
         }
         }
if(ch=='o'){
        if (jRadioButton2.isSelected()){ try
      {
       Class.forName("java.sql.Driver");
            System.out.println(30);
       Connection con=DriverManager.getConnection("jdbc:mysql://localhost/project","root","abcd");
            System.out.println(31);
       Statement stmt = con.createStatement();
            System.out.println(32);
       String query="update marks set marks=4 where qno="+15+";";
            System.out.println(query);
       stmt.executeUpdate(query);
            System.out.println(33);
            stmt.close();
            con.close();
          jButton5.doClick();  
       }
     catch (Exception e){
     JOptionPane.showMessageDialog(null, "error");
     }
         }
         }
    }//GEN-LAST:event_jRadioButton2ItemStateChanged

    private void jRadioButton4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton4ItemStateChanged
       char ch=jLabel16.getText().charAt(0);
       
if(ch=='g'){
        if (jRadioButton4.isSelected()){ try
      {
       Class.forName("java.sql.Driver");
            System.out.println(30);
       Connection con=DriverManager.getConnection("jdbc:mysql://localhost/project","root","abcd");
            System.out.println(31);
       Statement stmt = con.createStatement();
            System.out.println(32);
       String query="update marks set marks=4 where qno="+7+";";
            System.out.println(query);
       stmt.executeUpdate(query);
            System.out.println(33);
            stmt.close();
            con.close();
            
       }
     catch (Exception e){
     JOptionPane.showMessageDialog(null, "error");
     }
         }
         }
if(ch=='i'){
        if (jRadioButton4.isSelected()){ try
      {
       Class.forName("java.sql.Driver");
            System.out.println(30);
       Connection con=DriverManager.getConnection("jdbc:mysql://localhost/project","root","abcd");
            System.out.println(31);
       Statement stmt = con.createStatement();
            System.out.println(32);
       String query="update marks set marks=4 where qno="+9+";";
            System.out.println(query);
       stmt.executeUpdate(query);
            System.out.println(33);
            stmt.close();
            con.close();
            
       }
     catch (Exception e){
     JOptionPane.showMessageDialog(null, "error");
     }
         }
         }
if(ch=='l'){
        if (jRadioButton4.isSelected()){ try
      {
       Class.forName("java.sql.Driver");
            System.out.println(30);
       Connection con=DriverManager.getConnection("jdbc:mysql://localhost/project","root","abcd");
            System.out.println(31);
       Statement stmt = con.createStatement();
            System.out.println(32);
       String query="update marks set marks=4 where qno="+12+";";
            System.out.println(query);
       stmt.executeUpdate(query);
            System.out.println(33);
            stmt.close();
            con.close();
            
       }
     catch (Exception e){
     JOptionPane.showMessageDialog(null, "error");
     }
         }
         }
if(ch=='m'){
        if (jRadioButton4.isSelected()){ try
      {
       Class.forName("java.sql.Driver");
            System.out.println(30);
       Connection con=DriverManager.getConnection("jdbc:mysql://localhost/project","root","abcd");
            System.out.println(31);
       Statement stmt = con.createStatement();
            System.out.println(32);
       String query="update marks set marks=4 where qno="+13+";";
            System.out.println(query);
       stmt.executeUpdate(query);
            System.out.println(33);
            stmt.close();
            con.close();
            
       }
     catch (Exception e){
     JOptionPane.showMessageDialog(null, "error");
     }
         }
         }
    }//GEN-LAST:event_jRadioButton4ItemStateChanged

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        DefaultTableModel dtm=(DefaultTableModel) jTable1.getModel();
        int i,n=15;
        String question,ans;
        {try
      {
       Class.forName("java.sql.Driver");
            System.out.println(30);
       Connection con=DriverManager.getConnection("jdbc:mysql://localhost/project","root","abcd");
            System.out.println(31);
       Statement stmt = con.createStatement();
            System.out.println(32);
       String query="select qno from marks where marks is null;";
            System.out.println(query);
      ResultSet rs=stmt.executeQuery(query);
            System.out.println(33);
            while(rs.next()){
            int number=rs.getInt("qno");
         if(number==1)
         {question="How closer the satellite to earth the speed should be";
         ans="move slow";
         dtm.addRow(new Object[] {number,question,ans});}
         if(number==2)
         {question="The current enterring and leaving a point in a circuit should be";
         ans="increasing";
        
         dtm.addRow(new Object[] {number,question,ans});
         }
         if(number==3)
         {question="The process in which ac is converted to dc is called";
         ans="retrification";
         dtm.addRow(new Object[] {number,question,ans});}
         if(number==4)
         {question="unification of electromagnet and weak nuclear forces was done by :";
         ans="Abdus Salam";
         dtm.addRow(new Object[] {number,question,ans});}
         if(number==5)
         {question="I we get a straight line with a positive slopethen accceleration will be ";
         ans="Constant";
         dtm.addRow(new Object[] {number,question,ans});}
         if(number==6)
         {question="In a dry cell, the electrolyte paste is formed by ";
         ans="ammonium chloride";
         dtm.addRow(new Object[] {number,question,ans});}
         if(number==7)
         {question="Non conductors include";
         ans="both a and b";
         dtm.addRow(new Object[] {number,question,ans});}
         if(number==8)
         {question="With acid universal indicators show colour";
         ans="red";
         dtm.addRow(new Object[] {number,question,ans});}
         if(number==9)
         {question="The purpose o Lean Burn engine is to";
         ans="produce more efficient fuel combustion";
         dtm.addRow(new Object[] {number,question,ans});}
          
            if(number==10)
         {question="The ability of dissolving animal fat is found in";
         ans="liquid carbon dioxide";
         dtm.addRow(new Object[] {number,question,ans});}
            if(number==11)
         {question="What is the differential coeffiecient of cos(x)";
         ans="-sin(x)";
         dtm.addRow(new Object[] {number,question,ans});}
            if(number==12)
         {question="What is intgral of tan(x)";
         ans="both b and c";
         dtm.addRow(new Object[] {number,question,ans});}
            if(number==13)
         {question="What is the integral of sec(x)";
         ans="both a and c ";
         dtm.addRow(new Object[] {number,question,ans});}
            if(number==14)
         {question="which is true for eccentricity of hyperbola?";
         ans="e>1";
         dtm.addRow(new Object[] {number,question,ans});}
            if(number==15)
         {question="what is the integral of cot(x)";
         ans="log(cosec(x)-cot(x))";
         dtm.addRow(new Object[] {number,question,ans});}
            }
            rs.close();
            stmt.close();
            con.close();
            four.show();
       }
     catch (Exception e){
     JOptionPane.showMessageDialog(null, "error");
     }
         
     
    }//GEN-LAST:event_jButton6ActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton a;
    private javax.swing.JButton b;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton c;
    private javax.swing.JButton d;
    private javax.swing.JButton e;
    private javax.swing.JButton f;
    private javax.swing.JFrame four;
    private javax.swing.JButton g;
    private javax.swing.JButton h;
    private javax.swing.JButton i;
    private javax.swing.JButton j;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton k;
    private javax.swing.JButton l;
    private javax.swing.JButton m;
    private javax.swing.JButton n;
    private javax.swing.JButton o;
    private javax.swing.JFrame one;
    private javax.swing.JFrame three;
    private javax.swing.JFrame two;
    private javax.swing.JTextField txt1;
    // End of variables declaration//GEN-END:variables
}
